### GET ALL CARS
GET http://localhost:8080/api/carscatalog

### ADD NEW CAR
POST http://localhost:8080/api/carscatalog
Content-Type: application/json

{
  "brand": "Lamborghini",
  "model": "Huracan EVO",
  "yearOfProduction": 2020,
  "color": "Yellow",
  "engine": "V10 5.2L",
  "horsePower": 640,
  "price": 1300000
}

### FIND CARS BY BRAND
GET http://localhost:8080/api/carscatalog/searchByBrand?brand=lamborghinI

### FIND CARS BY YEAR OF PRODUCTION
GET http://localhost:8080/api/carscatalog/searchByYear?fromYear=1990&toYear=2003

### FIND CARS BY PRICE
GET http://localhost:8080/api/carscatalog/searchByPrice?fromPrice=1300000&toPrice=1300000

### DELETE CAR BY ID
DELETE http://localhost:8080/api/carscatalog/deleteById?id=3